### ISSUE TITLE
Workflow, file names

### ISSUE THREAD

**Issue by sthennin** [C-CINA/2dx#148]
Sections in 2dx_gui:

1) Import: Imports raw movies, which still need to be gain-reference applied, and which are non-square. Parameters start with "import_", such as "import_rawstack"

2) Library

3) Process: This one has the tabs for each opened image.

4) AutoProcess:  Here, the script "Parallel processing" should be found.

5) Merge

6) Particles

7) Export: Here, we should offer a script that allows to specify, where the data and parameters should be exported to. This could be drift-corrected stacks and images onto the mounted hard drive of the visiting guest, or movies and particles onto SciCORE's drives for FREALIGN or RELION runs with single particles or with Ricardo's 2D crystal single particles.   Or, this could be the final 3D map for EMDB upload, with FSC plots, etc..

**Comment by nikhilbiyani** [comment]
For easier navigation, we should place: IMPORT/EXPORT into the PROJECT and AutoProcess should appear as a permanent tab under Process! Otherwise the users may get confused when they want to change tabs and navigate, and which has to be done quite frequently when merging. Apart from that there should be a small separator between LIBRARY and others, just to differentiate that LIBRARY is the overview!
